# Generated by Django 2.0.7 on 2018-07-17 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20180717_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
