# Generated by Django 2.0.7 on 2018-07-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_message_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='loc',
            field=models.TextField(default='chn'),
        ),
    ]
