# Generated by Django 2.0.7 on 2018-07-17 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_message_loc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='loc',
            new_name='location',
        ),
    ]
